### ISSUE TITLE
Matrícula deve ser gerada automaticamente

### ISSUE THREAD

**Issue by abevieiramota** [gbraz/SistAcademicoJSF#16]
Devemos configurar o sistema para que a matrícula seja gerada automaticamente, quando na criação de um novo Aluno, utilizando um valor não utilizado ainda.

Pesquisar sobre Generators, GeneratedValue, sequences de banco de dados etc.

**Comment by gbraz** [comment]
Usei GeneratedValue
http://stackoverflow.com/questions/2011528/hibernate-auto-increment-id

**Comment by abevieiramota** [comment]
Lembrem do email :+1: 
Quem abre a issue é quem fecha :dancer:
