### ISSUE TITLE
Estudar a diferença entre $ e # na valoração da Expression Language

### ISSUE THREAD

**Issue by abevieiramota** [gbraz/SistAcademicoJSF#18]
Nos .xhtml, identifiquei o uso tanto de $ quanto #, como forma de realizar o bind de variáveis do managed bean(ver o confirma.xhtml). 

Buscar entender qual a diferença entre as duas formas e se estão sendo corretamente utilizados no sistema.

**Comment by gbraz** [comment]
O $ faz parte da sintaxe foreach do JSP, é uma eL (Expression Language), elas facilita o acesso dos atributos do Bean, substituindo o uso de getters e setters. Parece que antigamente eram usados scriptlets no lugar das eLs.
http://stackoverflow.com/questions/5736842/what-does-the-dollar-curly-brackets-mean-in-jsp
http://docs.oracle.com/javaee/1.4/tutorial/doc/JSPIntro7.html
http://www.tutorialspoint.com/jsp/jstl_core_foreach_tag.htm

O # é da sintaxe do JSF, também é um eL expression, mas enquanto o $ só pode fazer get, o # pode fazer get and set.
Melhor link pra entender: http://stackoverflow.com/tags/el/info 
cita até o JSR que eles foram especificadas.

**Comment by abevieiramota** [comment]
Ver http://docs.oracle.com/javaee/6/tutorial/doc/bnahr.html

**Comment by abevieiramota** [comment]
Issue atrasada :)

**Comment by gbraz** [comment]
- Immediate evalutation
  "Immediate evaluation means that the expression is evaluated and the result returned as soon as the page is first rendered".
  Ou seja, ela é executada apenas quando a página abre a primeira vez.
  Elas tem a forma ${}, e são apenas de leitura.
- Deferred evaluation
  "Deferred evaluation means that the technology using the expression language can use its own machinery to evaluate the expression sometime later during the page’s lifecycle, whenever it is appropriate to do so.".
  Ou seja, pode ser executada enquanto a página estiver aberta.
  Elas tem a forma #{}, podem ser usadas tanto para leitura como para escrita de valores, e também aceita métodos.
