### ISSUE TITLE
Estudar sobre escopos no JSF

### ISSUE THREAD

**Issue by abevieiramota** [gbraz/SistAcademicoJSF#19]
Estudar os escopos definidos no JSF 2, principalmente onde aplicá-los.
View, Request, Session, Application, None, Custom
[Communication in JSF 2.0](http://balusc.blogspot.com.br/2011/09/communication-in-jsf-20.html#ManagedBeanScopes)

**Comment by gbraz** [comment]
@RequestScoped - o Bean só dura enquanto a HTTP request-response perdurar.
@ViewScoped - o Bean dura enquanto você estiver interagindo com a JSF view no browser
@SessionScoped - o Bean dura enquanto a sessão do HTTP durar, e é destruido quando essa sessão HTTP é invalidada ou é removido "manualmente".
@ApplicaitonScoped - o Bean dura enquanto a aplicação viver ou se for removido "manualmente".
@NoneScoped - o Bean dura apenas por uma EL (expression language) 
@CustomScoped - o Bean dura o enquanto existir uma referencia a ele no Map que foi criado para esse escopo durar.
