### ISSUE TITLE
Hashmap não é ótimo para percorrer

### ISSUE THREAD

**Issue by Maysk** [gbraz/SistAcademicoJSF#2]
Achamos uma solução, mas ela não parece ser correta. 
Há opção de usar outra estrutura também.

**Comment by gbraz** [comment]
HashMap não é a estrutura ideal se for usada uma operação que percorra toda a tabela em busca de alunos.
Por mim, ou trocava a estrutura ou não percorre a lista.

**Comment by abevieiramota** [comment]
Por quê?
Lembrem do [Act with Prudence](http://programmer.97things.oreilly.com/wiki/index.php/Act_with_Prudence)
**Map**, herdando de **Collections**, possui o método [Map#values()](http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#values%28%29), que permite que sejam percorridos os valores neles contidos.

**Comment by gbraz** [comment]
Pelo que entendi esse método retorna outro objeto do tipo Collections. Meu maior problema com essa idéia é que teremos duas estruturas pra lidar com o mesmo conjunto de dados, o que para mim parece o caso de escolha errada de estrutura de dados.

**Comment by abevieiramota** [comment]
Não! Map implementa a interface Collections!
Ele pode ser visto também como um Collections. 
Para listar os dados, é suficiente um método que retorne os valores, que é o que o método **values()** de Collections faz.
Map foi utilizado pela necessidade de haver uma associação entre matrícula e Aluno, com eficiência no tempo de recuperação deste a partir daquele!

**Comment by abevieiramota** [comment]
Dêem uma olhada nos links:

http://www.programcreek.com/2009/02/the-interface-and-class-hierarchy-for-collections/
http://en.wikipedia.org/wiki/Java_collections_framework
