### ISSUE TITLE
Tela de Index

### ISSUE THREAD

**Issue by Maysk** [gbraz/SistAcademicoJSF#22]
-Menu drop 
-Aluno
-Curso
-Matricular

**Comment by gbraz** [comment]
https://myfaces.apache.org/tomahawk-project/tomahawk12/tagdoc/t_jscookMenu.html
Um problema encontrado foi a action não estava sendo executada do jscookMenu, encontrei a solução aqui:
http://stackoverflow.com/questions/9034640/tomahawk-jscookmenu-does-not-trigger-any-actions-after-upgrading-to-jsf2
http://www.guj.com.br/java/49109-jscookmenu-do-tomahawk

**Comment by abevieiramota** [comment]
Removido dessa iteração a matrícula
