### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by abevieiramota** [gbraz/SistAcademicoJSF#7]
Pesquisar sobre cobertura de código(code coverage) e buscar ferramenta para realizar análise de cobertura de código neste projeto.

**Comment by abevieiramota** [comment]
Adicionar as informações sobre a ferramenta utilizada.

**Comment by Maysk** [comment]
Foi utilizado um plugin do Eclipse chamado EclEmma: http://www.eclemma.org/
