### ISSUE TITLE
Utilizar JPA+Hibernate

### ISSUE THREAD

**Issue by abevieiramota** [gbraz/SistAcademicoJSF#9]
Refatorar o sistema para utilizar, no lugar de Map, um banco de dados, com acesso via JPA+Hibernate.

De preferência, utilizar um banco de dados simples, como o sqlite3.

Nesse momento não é preciso se preocupar com padrões como DAO.

**Comment by Maysk** [comment]
O que eu disse que havia visto:
http://stackoverflow.com/questions/17587753/does-hibernate-fully-support-sqlite

**Comment by abevieiramota** [comment]
Uma coisa que disse ontem e repito: fazer o mínimo para satisfazer o requisito!
Simplicidade! Aqui volta a questão de documentação: quanto mais documentos, mais artefatos para se manter! Fazendo apenas o que é necessário, a motivação para manter é natural. Se a necessidade de manter algo que você desenvolveu não aparece naturalmente, provavelmente é algo desnecessário. Novamente o exemplo da documentação: se você documenta um método e percebe que começa a evoluir o código sem evoluir a documentação, provavelmente a documentação não representa um valor importante o suficiente para justificar sua existência, seja pela sua imaturidade em trabalhar com código documentado, seja pela não necessidade em si de documentação.
É o que disse, ainda mais pra vocês que ainda estão verdinhos hehe: é melhor fazer uma merda grande e entender por que ela fede do que começar a perfumar tudo sem entender o porquê e, eventualmente, acabar perfumando demais e ficando mais fedorento ainda!

**Comment by abevieiramota** [comment]
Um dos próximos passos então vai ser mudar o sgbd de MySQL para algum embeddable, como o H2 ou o HSQLDB.
Bom para verificar se o uso de um padrão(JPA) com drivers realmente facilita a mudança de sgbd.
